# Generated by Django 5.2.12 on 2026-03-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(blank=True, default='', max_length=17)),
                ('rotate', models.BooleanField(default=False)),
                ('negative', models.BooleanField(default=False)),
                ('dithering', models.CharField(choices=[('none', 'None'), ('floydsteinberg', 'Floyd-Steinberg'), ('combined', 'Combined')], default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EpaperImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='epaper_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
