# Generated by Django 5.2.12 on 2026-03-27 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epaper", "0003_deviceconfig_ical_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceconfig",
            name="automation_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable automatic switching based on iCal status",
            ),
        ),
        migrations.AddField(
            model_name="deviceconfig",
            name="ical_busy_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to show when in a meeting",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="busy_configs",
                to="epaper.epaperimage",
            ),
        ),
        migrations.AddField(
            model_name="deviceconfig",
            name="ical_free_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to show when no meetings are active",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="free_configs",
                to="epaper.epaperimage",
            ),
        ),
        migrations.AddField(
            model_name="deviceconfig",
            name="last_automation_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_automated",
                to="epaper.epaperimage",
            ),
        ),
    ]
