# Generated by Django 5.2.12 on 2026-03-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0004_deviceconfig_automation_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='last_automation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
