# Generated by Django 5.2.12 on 2026-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epaper", "0005_deviceconfig_last_automation_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceconfig",
            name="pollinations_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="API Key for pollinations.ai image generation",
                max_length=255,
            ),
        ),
    ]
