# Generated by Django 5.2.12 on 2026-04-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epaper", "0007_deviceconfig_pollinations_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceconfig",
            name="pollinations_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kontext", "kontext"),
                    ("nanobanana", "nanobanana"),
                    ("nanobanana-2", "nanobanana-2"),
                    ("nanobanana-pro", "nanobanana-pro"),
                    ("seedream5", "seedream5"),
                    ("seedream", "seedream"),
                    ("seedream-pro", "seedream-pro"),
                    ("gptimage", "gptimage"),
                    ("gptimage-large", "gptimage-large"),
                    ("flux", "flux"),
                    ("zimage", "zimage"),
                    ("veo", "veo"),
                    ("seedance", "seedance"),
                    ("seedance-pro", "seedance-pro"),
                    ("wan", "wan"),
                    ("wan-fast", "wan-fast"),
                    ("wan-image", "wan-image"),
                    ("wan-image-pro", "wan-image-pro"),
                    ("qwen-image", "qwen-image"),
                    ("grok-imagine", "grok-imagine"),
                    ("grok-imagine-pro", "grok-imagine-pro"),
                    ("grok-video-pro", "grok-video-pro"),
                    ("klein", "klein"),
                    ("ltx-2", "ltx-2"),
                    ("p-image", "p-image"),
                    ("p-image-edit", "p-image-edit"),
                    ("p-video", "p-video"),
                    ("nova-canvas", "nova-canvas"),
                    ("nova-reel", "nova-reel"),
                ],
                default="flux",
                max_length=50,
            ),
        ),
    ]
